### ISSUE TITLE
Feat: Compatibility with BetterF3

### ISSUE THREAD

**Issue by Shywizz** [Minenash/Independent-Gizmo#5]
I don't really know if mixin wise this is something that could be done but betterF3 seems to also change some code with the gizmo which causes a crash when both are loaded, 
What i would like is that the gizmo can still be toggled and takes precedence over betterF3 gizmo changes/settings
Like i said, i have modified a single mixin once like three months ago, so i don't know how feasable this is

**Comment by Ryltarr** [comment]
I think it could be done with just changing the mixin priority to be higher for this mod...? But ultimately, I don't know enough about it. I'm looking into trying to create a betterF3 fork which contains this info and hopefully I can merge it in...? But I'm literally brand new to java modding.
