### ISSUE TITLE
Option to remember last state of gizmo

### ISSUE THREAD

**Issue by pointydev** [Minenash/Independent-Gizmo#8]
Hey there,

Love this mod simply because it shows the attack indicator alongside the gizmo, however I have a feature suggestion: Add the an option to remember the last state of the gizmo.

Personally I almost always have it enabled, and would prefer to not have to toggle the gizmo on at the start of every new session. Alternatively, instead of remembering the last state, you could add an option to set the default state of the gizmo.

Thanks,
pointy

**Comment by Minenash** [comment]
Added in v1.1.0 (though it's not an option, it just is persistent)
